### ISSUE TITLE
[vue2.7 web-types] 我想咨询一下关于在vue2.7的情况下如何定义组件的补全功能？

### ISSUE THREAD

**Issue by RSS1102** [kingyue737/vitify-admin#19]
你好，我看到你在[volar的pr](https://github.com/johnsoncodehk/volar/pull/1747)中提及了怎么定义vue2.7的代码的提示和补全。

---
同时我看到你为组件vuetify提供了[issue](https://github.com/vuetifyjs/vuetify/issues/14798#issuecomment-1139788615)。
但是当我在vue2.7内使用vuetify并且安装了volar插件，并没有获得代码补全的能力。

---
但是我在这个项目[vitify-admin](https://github.com/kingyue737/vitify-admin)内使用时却可以获得一定的代码补全和提示能力，所以我想问这个能力是如何进行的，他和vuetify的有何不同，谢谢。

**Comment by kingyue737** [comment]
代码提示和补全来源于vuetify组件的TypeScript类型，但是vuetify2**没有自带**的组件类型定义。你可以在[这里](https://unpkg.com/browse/vuetify@2.6.12/types/lib.d.ts)看到所有组件的类型都是`VueConstructor`，没有任何关于组件的prop和slot的类型。

所以关键在于创建这些组件的正确类型，提供给volar来产生模板中的补全和类型检查。vuetify2的官网文档是从[`web-types.json`](https://unpkg.com/browse/vuetify@2.6.12/dist/json/web-types.json)这个文件生成的，里面有相对完备的组件prop和slot的定义，我就写了一个[脚本](https://github.com/kingyue737/vitify-admin/blob/main/scripts/vuetify-type.mjs)用它生成了[TypeScript类型声明文件](https://github.com/kingyue737/vitify-admin/blob/main/src/vuetify2.d.ts)。

你可以把这里已经生成好的`d.ts`文件复制到你的项目里，或者把上面提到的那个脚本复制到你的项目里跑一下自己来生成`d.ts`（好处是如果官方更新了`web-types.json`，你只要再跑一下脚本就能获得最新的组件类型）。

**Comment by RSS1102** [comment]
好的，非常感谢您的指导，我看一下。
