### ISSUE TITLE
The project takes 3 to 10min to launch

### ISSUE THREAD

**Issue by Neogeekmo** [kingyue737/vitify-admin#21]
After downloading the project without making any changes. 

The `pnpm dev` 4282ms to load fast (which is acceptable) but the UI takes between 3 to 10 min to load. 
![image](https://user-images.githubusercontent.com/28711160/210757224-de373c77-f624-440b-97fb-79a4b7a770a5.png)

here ~3min 
![image](https://user-images.githubusercontent.com/28711160/210760269-ca360093-7115-4f09-9c5f-567f6f8dce2e.png)

I don't understand why it has been idle for so long
Is there a particular config that can create this kind of problem?

**Comment by kingyue737** [comment]
On my computer, it took 80 seconds for first start which seems reasonable as there are some large dependencies like `echarts` and `vuetify`. Custom SCSS of Vuetify is also compiled on-the-fly which takes long time. During the first launch, vite optimzed and cached all the dependencies. Then you will find the site appear instantly next time you launch the dev server of vite. 

Slow first start seems to be a long-standing issue of Vite https://github.com/vitejs/vite/issues/7608#issuecomment-1087672218

But 3 to 10 mins seems unacceptable. What's the parameters of your computer?

Mine:
```
System:
    OS: Windows 10 10.0.22000
    CPU: (6) x64 Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz
    Memory: 2.31 GB / 15.86 GB
```

**Comment by Neogeekmo** [comment]
I just closed and restarted the dev server and it take ~3min again. 

```
    OS: Windows 10 Pro 10.0.19044
    CPU: 12th Gen Intel(R) Core(TM) i7-1265U   1.80 GHz
    Memory: 10.7 GB / 15.7GB
```

**Comment by profispojka** [comment]
Same problem. Large codebase. Cannot start cypress tests (with webpack, they worked)

**Comment by kingyue737** [comment]
If you need a lightweight template, I made [one](https://github.com/kingyue737/vitify-next) but with Vue 3 + Vuetify 3. Feel free to try it.
