### ISSUE TITLE
[vite-plugin-pages] Provide an example for Dynamic Routes

### ISSUE THREAD

**Issue by Neogeekmo** [kingyue737/vitify-admin#22]
## Question
Could you add an example in the template to use the dynamic routes of the [[vite-plugin-pages]](https://github.com/hannoeru/vite-plugin-pages) plugin. 

## Example

It could use the user-manage page with the possibility to go on a user subpage  by passing for example his ID or Username in the url

A route like that => `src/pages/user-manage/[id].vue -> /user-manage/:id (/user-manage/kingyue737)`

Tree: 
```
src/pages/
  ├── user-manage/
  │  └── [id].vue
  └── user-manage.vue
  ```
  
## Issue
It doesn't seem to work with the template, that's why I'm asking because there might be a config issue or a conflict with an other plugin

**Comment by kingyue737** [comment]
Hi @Neogeekmo , example added via 5d39fff and updated on [demo](https://vitify-admin.netlify.app/user-manage/). You can click username in datatable to enter the subpage and return to datatable via breadcrumb.

**Comment by Neogeekmo** [comment]
thx a lot <3
