### ISSUE TITLE
Do we need to specify editorconfig in .prettierrc?

### ISSUE THREAD

**Issue by paolodina** [kingyue737/vitify-admin#6]
Hi and thanks for the wonderful work you did.

After cloning the repo and open some file I see a lot of prettier warnings like

![image](https://user-images.githubusercontent.com/1157401/188588665-3089d089-4b92-47d4-bbd9-2b32bf473d1e.png)

Not a huge problem, but I tried to run prettier manually getting another kind of warning
```bash
$ pnpm exec prettier --check src/*
Checking formatting...
[warn] Ignored unknown option { editorconfig: true }.
[warn] src/api/users.ts
[warn] Ignored unknown option { editorconfig: true }.
[warn] src/App.vue
...etc...
```

Now:
- is it possible to fix all the prettier issues and commit the "fixed" code so we don't have to manually run prettier just after cloning the repo?
- it should be possible to remove `editorconfig` from `.prettierrc`, (https://github.com/prettier/prettier/issues/6176#issuecomment-498808239). I tried and seems to work well.
- maybe worth to add a custom script to `package.json` to run prettier

**Comment by paolodina** [comment]
It's also uncommon that after prettier has run, adding the fixed files to git gives:

```
$ git add .
...
warning: CRLF will be replaced by LF in src/components/layout/AppBreadcrumbs.vue.
The file will have its original line endings in your working directory
warning: CRLF will be replaced by LF in src/components/layout/AppDrawer.vue.
The file will have its original line endings in your working directory
...
```

**Comment by kingyue737** [comment]
Thank you very much, @paolodina ! 
You are right. `editorconfig` can be removed from `.prettierrc` as it will always be read by Prettier. I've never used Prettier CLI before, so I didn't notice this issue. We use [Prettier extension](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) and source files are automatically formatted when saved. It's a good idea to add a custom script to `package.json` or benefit git hooks to format code.

As all of my teammates are coding on Windows, I set `eol` to `crlf`. If you are using Linux, it is recommended to set `lf` as `eol` in `.editorconfig`.
```
end_of_line = lf
```

You can also select eol on status bar of VSCode.

![image](https://user-images.githubusercontent.com/40021217/188596176-331dc1be-5534-44f4-abba-f08592dee36c.png)

> warning: CRLF will be replaced by LF

As for the warning, I cannot reproduce it on my computer. I will investigate how to avoid this warning on different OS and with different git config. Maybe we should prevent git from converting eol.

**Comment by kingyue737** [comment]
Oh I forgot one thing. Maybe we don't need a custom prettier script, because we already have `pnpm lint`. 
ESlint in this template is configured with [`eslint-plugin-prettier`](https://github.com/prettier/eslint-plugin-prettier#options).

If you run `pnpm lint`, your code will be formatted according to prettier style.

**Comment by paolodina** [comment]
All clear, thanks!
